services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: ecommerce-qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ASP.NET Core Application
  ecommerce-app:
    build:
      context: .
      dockerfile: EcommerceAppAI/Dockerfile
    container_name: ecommerce-app
    ports:
      - "5265:8080"  # Only HTTP for simplicity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080  # Only HTTP binding
      - LlmSettings__BaseUrl=http://host.docker.internal:1234
    networks:
      - ecommerce-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Access host machine LM Studio

volumes:
  qdrant_data:
    driver: local

networks:
  ecommerce-network:
    driver: bridge