services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: ecommerce-qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

  # ASP.NET Core Application
  ecommerce-app:
    build:
      context: .
      dockerfile: EcommerceAppAI/Dockerfile
    container_name: ecommerce-app
    ports:
      - "5265:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - LlmSettings__BaseUrl=http://host.docker.internal:11434
      - QdrantSettings__ConnectionString=http://qdrant:6334
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  qdrant_data:
    driver: local